# Generated by Django 6.0.1 on 2026-01-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_remove_userprofile_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'superadmin'), ('customer', 'customer')], db_index=True, max_length=32),
        ),
    ]
